services:
  # MongoDB Replica Set Node
  mongodb:
    image: mongo:8.0.23
    container_name: mongodb_service
    restart: always
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=tTFttAuchFoCEHttNHLfszk6
    volumes:
      - mongo_data:/data/db
      - ./mongo-key/mongo-keyfile:/etc/mongo-keyfile:ro
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile"]

  # Init-replica: Temporary container to run rs.initiate()
  mongodb-init:
    image: mongo:8.0.23
    container_name: mongodb_init
    depends_on:
      - mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=tTFttAuchFoCEHttNHLfszk6
    entrypoint:
      [
        "/bin/bash",
        "-c",
        'sleep 10 && mongosh --host mongodb -u admin -p tTFttAuchFoCEHttNHLfszk6 --eval "rs.initiate({_id: ''rs0'', members: [{_id: 0, host: ''mongodb:27017''}]})" && echo "Waiting for primary election..." && for i in $(seq 1 30); do mongosh --host mongodb -u admin -p tTFttAuchFoCEHttNHLfszk6 --quiet --eval "rs.status().members[0].stateStr === ''PRIMARY''" 2>/dev/null | grep -q true && echo "Primary elected!" && break; sleep 2; done'
      ]

  # Express application
  app:
    build: ./app
    container_name: express_app
    restart: always
    environment:
      - MONGO_URI=mongodb://admin:tTFttAuchFoCEHttNHLfszk6@mongodb:27017/my-mongo-db?authSource=admin&replicaSet=rs0
    depends_on:
      - mongodb
      - mongodb-init
    ports:
      - "3000:3000"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  mongo_data:
    driver: local
